version: '3'
services:
  python:
    # image: python:3.7
    # container_name: python_dev2
    # tty: true
    container_name: "app"
    build: ./app
    volumes:
      - ./app/source:/app/source
      - ./app/data:/app/data